name: PG migration

on: pull_request

jobs:
  migrate_pg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: '${{ secrets.GCP_CREDENTIALS }}'
          instance: buildcore-test:us-central1:buildcore-test
      - name: RUn
        run: |
          npm i
          npm run build 
          npm run start
