name: Test Secrets

on:
  push:

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars
        working-directory: packages/functions
        run: |
          echo "$MY_SECRET" >> .env
          cat .env
        env:
          MY_SECRET: ${{ secrets.TEST }}
