name: Release test

on:
  release:
    types: [published]

on:
  push:

jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Set env varsx
        run: |
          echo ${{ github.event.release.tag_name }}
          echo ${{ github.event.release.body }}