name: Release test

on:
  release:
    types: [created]

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo ${{ github.event.release.tag_name }}
          echo ${{ github.event.release.body }}
